-! 04/10/19 23:38:58.960 server.py: warning: dispatch exception: src\Util.cpp:344: ::Ice::UnknownException:
   unknown exception:
   Traceback (most recent call last):
     File "C:\Program Files\Python37\lib\site-packages\Ice\__init__.py", line 408, in _iceDispatch
       result = method(*args)
     File "server.py", line 91, in jouerTitres
       player = media_list_player_new()
   NameError: name 'media_list_player_new' is not defined
   
   identity: SimpleManager
   facet: 
   operation: jouerTitres
   remote host: ::ffff:127.0.0.1 remote port: 53752
-! 04/11/19 00:05:56.350 server.py: warning: connection exception:
   src\ice\cpp\src\Ice\StreamSocket.cpp:483: ::Ice::ConnectionLostException:
   connection lost: recv() returned zero
   local address = ::ffff:127.0.0.1:10000
   remote address = ::ffff:127.0.0.1:54221
-! 04/11/19 00:14:47.648 server.py: warning: connection exception:
   src\ice\cpp\src\Ice\StreamSocket.cpp:483: ::Ice::ConnectionLostException:
   connection lost: recv() returned zero
   local address = ::ffff:127.0.0.1:10000
   remote address = ::ffff:127.0.0.1:54471
-! 04/11/19 00:15:17.057 server.py: warning: connection exception:
   src\ice\cpp\src\Ice\StreamSocket.cpp:483: ::Ice::ConnectionLostException:
   connection lost: recv() returned zero
   local address = ::ffff:127.0.0.1:10000
   remote address = ::ffff:127.0.0.1:54478
-! 04/11/19 00:23:26.471 server.py: warning: connection exception:
   src\ice\cpp\src\Ice\StreamSocket.cpp:483: ::Ice::ConnectionLostException:
   connection lost: recv() returned zero
   local address = ::ffff:127.0.0.1:10000
   remote address = ::ffff:127.0.0.1:54761
-! 04/11/19 00:24:13.201 server.py: warning: connection exception:
   src\ice\cpp\src\Ice\StreamSocket.cpp:483: ::Ice::ConnectionLostException:
   connection lost: recv() returned zero
   local address = ::ffff:127.0.0.1:10000
   remote address = ::ffff:127.0.0.1:54797
-! 04/11/19 00:39:20.135 server.py: warning: dispatch exception: src\Util.cpp:344: ::Ice::UnknownException:
   unknown exception:
   Traceback (most recent call last):
     File "C:\Program Files\Python37\lib\site-packages\Ice\__init__.py", line 408, in _iceDispatch
       result = method(*args)
     File "server.py", line 90, in jouerTitres
       media = vlcInst.media_list_new(localTracks, stream)
   TypeError: media_list_new() takes from 1 to 2 positional arguments but 3 were given
   
   identity: SimpleManager
   facet: 
   operation: jouerTitres
   remote host: ::ffff:127.0.0.1 remote port: 55494
-! 04/11/19 00:45:22.658 server.py: warning: connection exception:
   src\ice\cpp\src\Ice\StreamSocket.cpp:483: ::Ice::ConnectionLostException:
   connection lost: recv() returned zero
   local address = ::ffff:127.0.0.1:10000
   remote address = ::ffff:127.0.0.1:55705
-! 04/11/19 01:09:18.594 server.py: warning: connection exception:
   src\ice\cpp\src\Ice\StreamSocket.cpp:474: ::Ice::ConnectionLostException:
   connection lost: Le nom réseau spécifié n’est plus disponible.
   local address = ::ffff:127.0.0.1:10000
   remote address = ::ffff:127.0.0.1:56689
-! 04/23/19 17:06:10.090 server.py: warning: dispatch exception: src\Util.cpp:344: ::Ice::UnknownException:
   unknown exception:
   Traceback (most recent call last):
     File "C:\Program Files\Python37\lib\site-packages\Ice\__init__.py", line 408, in _iceDispatch
       result = method(*args)
     File "server.py", line 88, in jouerTitres
       media = vlcInst.media_list_new(localTracks, 'sout=#transcode{vcodec=none,acodec=mp3,ab=128,channels=2,samplerate=44100,scodec=none}:http{mux=mp3,dst=:10000/}', 'no-sout-all', 'sout_keep')
   TypeError: media_list_new() takes from 1 to 2 positional arguments but 5 were given
   
   identity: SimpleManager
   facet: 
   operation: jouerTitres
   remote host: ::ffff:127.0.0.1 remote port: 55387
-! 04/23/19 17:07:53.406 server.py: warning: dispatch exception: src\Util.cpp:344: ::Ice::UnknownException:
   unknown exception:
   Traceback (most recent call last):
     File "C:\Program Files\Python37\lib\site-packages\Ice\__init__.py", line 408, in _iceDispatch
       result = method(*args)
     File "server.py", line 88, in jouerTitres
       media = vlcInst.media_list_new(localTracks, 'sout=#transcode{vcodec=none,acodec=mp3,ab=128,channels=2,samplerate=44100,scodec=none}:http{mux=mp3,dst=:10000/}', 'no-sout-all', 'sout_keep')
   TypeError: media_list_new() takes from 1 to 2 positional arguments but 5 were given
   
   identity: SimpleManager
   facet: 
   operation: jouerTitres
   remote host: ::ffff:127.0.0.1 remote port: 55461
-! 04/23/19 17:14:12.390 server.py: warning: dispatch exception: src\Util.cpp:344: ::Ice::UnknownException:
   unknown exception:
   Traceback (most recent call last):
     File "C:\Program Files\Python37\lib\site-packages\Ice\__init__.py", line 408, in _iceDispatch
       result = method(*args)
     File "server.py", line 88, in jouerTitres
       media = vlcInst.media_list_new('sout=#transcode{vcodec=none,acodec=mp3,ab=128,channels=2,samplerate=44100,scodec=none}:http{mux=mp3,dst=:10000/}', 'no-sout-all', 'sout_keep')
   TypeError: media_list_new() takes from 1 to 2 positional arguments but 4 were given
   
   identity: SimpleManager
   facet: 
   operation: jouerTitres
   remote host: ::ffff:127.0.0.1 remote port: 55682
-! 04/23/19 17:15:40.796 server.py: warning: dispatch exception: src\Util.cpp:344: ::Ice::UnknownException:
   unknown exception:
   Traceback (most recent call last):
     File "C:\Program Files\Python37\lib\site-packages\Ice\__init__.py", line 408, in _iceDispatch
       result = method(*args)
     File "server.py", line 88, in jouerTitres
       media = vlcInst.media_list_new('sout=#transcode{vcodec=none,acodec=mp3,ab=128,channels=2,samplerate=44100,scodec=none}:http{mux=mp3,dst=:10000/}', 'no-sout-all', 'sout_keep')
   TypeError: media_list_new() takes from 1 to 2 positional arguments but 4 were given
   
   identity: SimpleManager
   facet: 
   operation: jouerTitres
   remote host: ::ffff:127.0.0.1 remote port: 55736
-! 04/23/19 17:20:17.288 server.py: warning: dispatch exception: src\Util.cpp:344: ::Ice::UnknownException:
   unknown exception:
   Traceback (most recent call last):
     File "C:\Program Files\Python37\lib\site-packages\Ice\__init__.py", line 408, in _iceDispatch
       result = method(*args)
     File "server.py", line 88, in jouerTitres
       media = vlcInst.media_list_new(localTracks, 'sout=#transcode{vcodec=none,acodec=mp3,ab=128,channels=2,samplerate=44100,scodec=none}:http{mux=mp3,dst=:10000/stream}', 'no-sout-all', 'sout_keep')
   TypeError: media_list_new() takes from 1 to 2 positional arguments but 5 were given
   
   identity: SimpleManager
   facet: 
   operation: jouerTitres
   remote host: ::ffff:127.0.0.1 remote port: 55878
-! 04/23/19 17:40:09.354 server.py: warning: dispatch exception: src\Util.cpp:344: ::Ice::UnknownException:
   unknown exception:
   Traceback (most recent call last):
     File "C:\Program Files\Python37\lib\site-packages\Ice\__init__.py", line 408, in _iceDispatch
       result = method(*args)
     File "server.py", line 88, in jouerTitres
       media = vlcInst.media_list_new(localTracks, 'sout=#transcode{vcodec=none,acodec=mp3,ab=128,channels=2,samplerate=44100,scodec=none}:http{mux=mp3,dst=:10000/stream}', 'sout-all', 'sout_keep')
   TypeError: media_list_new() takes from 1 to 2 positional arguments but 5 were given
   
   identity: SimpleManager
   facet: 
   operation: jouerTitres
   remote host: ::ffff:127.0.0.1 remote port: 56553
-! 04/23/19 17:41:35.895 server.py: warning: dispatch exception: src\Util.cpp:344: ::Ice::UnknownException:
   unknown exception:
   Traceback (most recent call last):
     File "C:\Program Files\Python37\lib\site-packages\Ice\__init__.py", line 408, in _iceDispatch
       result = method(*args)
     File "server.py", line 88, in jouerTitres
       media = vlcInst.media_list_new(localTracks, 'sout=#transcode{vcodec=none,acodec=mp3,ab=128,channels=2,samplerate=44100,scodec=none}:http{mux=mp3,dst=:10000/stream}', 'sout-all', 'sout_keep')
   TypeError: media_list_new() takes from 1 to 2 positional arguments but 5 were given
   
   identity: SimpleManager
   facet: 
   operation: jouerTitres
   remote host: ::ffff:127.0.0.1 remote port: 56602
